# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test Upload Python Package

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
        contents: read  # This is required for actions/checkout
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python -m build
    
  pypi-publish:
    name: Publish package
    runs-on: ubuntu-latest
    needs: deploy
    permissions:
        id-token: write
    steps:
    - name: Publishing at TestPyPi
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYNAFF_TESTPYPI_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
